authentication/urls.py
from django.urls import path

from . import views


app_name = "authentication"

urlpatterns = [
    path('login/', views.login_user, name='login'),
    path('register/', views.register, name='register'),
    path('logout_user/', views.logout_user, name='logout_user'),
    path('activate-user/<uidb64>/<token>/', views.activate_user, name="activate"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todo.urls')),
    path('auth/', include('authentication.urls')),
]

handler404 = "helper.views.handle_not_found"
handler500 = "helper.views.handle_server_error"

todo/urls.py
from django.urls import path

from . import views

app_name = "todo"

urlpatterns = [
    path('', views.index, name='home'),
    path('create-todo/', views.create_todo, name='create-todo'),
    path('detail-todo/<int:id>/', views.todo_detail, name='todo-detail'),
    path('delete-todo/<int:id>/', views.todo_delete, name='todo-delete'),
    path('edit-todo/<int:id>/', views.todo_edit, name='todo-edit'),
]

templates/_partials/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}

        {% endblock %}
    </title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css" integrity="sha512-8bHTC73gkZ7rZ7vpqUQThUDhqcNFyYi2xgDgPDHc+GXVGHXq+xPjynxIopALmOPqzo9JZj0k6OqqewdGO3EsrQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
<div>
  {% include '_partials/header.html' %}
    <div class="ui container">
        {% block content %}

        {% endblock %}
    </div>

</div>
</body>
</html>

templates/_partials/header.html
{% load static %}
<div class="ui menu">
    <div class="ui container">
        <a href="{% url 'todo:home' %}" class="header item">
            <img class="logo" class="logo" src="{% static 'images/Logo.png' %}"/>
        </a>


        <div class="right item">

            {% if request.user.is_authenticated %}
            <a href="{% url 'todo:create-todo' %}" class="ui primary button">Create Todo</a>
            <div class="ui simple dropdown item">
                {{request.user.username}} <i class="dropdown icon"></i>
                <div class="menu">
                    <form class="ui large form" method="post" action="{% url 'authentication:logout_user' %}">

                        {% csrf_token %}
                        <input class="ui button"
                               type="submit"
                               value="Sign out"
                        />
                    </form>
                </div>
            </div>

            {% else %}
            <div class="ui item">
                <a href="{% url 'authentication:login' %}" class="ui primary button">Login</a>
            </div>

            <div class="ui item">
                <a href="{% url 'authentication:register' %}" class="ui primary button">Register</a>
            </div>

            {% endif %}
        </div>
    </div>
</div>

templates/_partials/messages.html
{% if messages %}

  {% for message in messages %}
      <div class="ui {{message.tags}} message">
        {{message}}
      </div>
  {% endfor %}

{% endif %}