core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todo.urls')),
    path('auth/', include('authentication.urls')),
]

handler404 = "helper.views.handle_not_found"
handler500 = "helper.views.handle_server_error"

todo/urls.py
from django.urls import path

from . import views

app_name = "todo"

urlpatterns = [
    path('', views.index, name='home'),
    path('create-todo/', views.create_todo, name='create-todo'),
    path('detail-todo/<int:id>/', views.todo_detail, name='todo-detail'),
    path('delete-todo/<int:id>/', views.todo_delete, name='todo-delete'),
    path('edit-todo/<int:id>/', views.todo_edit, name='todo-edit'),
]

todo/models.py
from django.db import models

from authentication.models import User
from helper.models import TrackingModel


class Todo(TrackingModel):
    title = models.CharField(max_length=255)
    description = models.TextField()
    is_completed = models.BooleanField(default=False)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

todo/forms.py
from django import forms

from .models import Todo


class TodoForm(forms.ModelForm):

    class Meta:
        model = Todo

        fields = ["title", "description", "is_completed"]

todo/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from .forms import TodoForm
from .models import Todo


def get_showing_todos(request, todos):

    if request.GET and request.GET.get('filter'):
        if request.GET.get("filter") == "complete":
            return todos.filter(is_completed=True)
        if request.GET.get("filter") == "incomplete":
            return todos.filter(is_completed=False)

    return todos


@login_required()
def index(request):
    todos = Todo.objects.filter(owner=request.user)

    completed_count = todos.filter(is_completed=True).count()
    incomplete_count = todos.filter(is_completed=False).count()
    all_count = todos.count()

    context = {
        'todos': get_showing_todos(request, todos),
        'all_count': all_count,
        'completed_count': completed_count,
        'incomplete_count': incomplete_count
    }
    return render(request, 'todo/index.html', context)


def create_todo(request):
    form = TodoForm()
    context = {
        'form': form
    }
    if request.method == 'POST':
        title = request.POST.get('title')
        description = request.POST.get('description')
        is_completed = request.POST.get('is_completed', False)

        todo = Todo.objects.create(title=title, description=description
                                   , is_completed=True if is_completed == "on" else False
                                   ,owner=request.user)

        todo.save()
        messages.add_message(request, messages.SUCCESS, "Todo created success")
        return HttpResponseRedirect(reverse('todo:todo-detail', kwargs={'id': todo.pk}))

    return render(request, 'todo/create-todo.html', context)


@login_required
def todo_detail(request, id):
    todo = get_object_or_404(Todo, pk=id)
    context = {
        'todo': todo
    }
    return render(request, "todo/todo-detail.html", context)


def todo_delete(request, id):
    todo = get_object_or_404(Todo, pk=id)
    context = {
        'todo': todo
    }

    if request.method == 'POST':
        if todo.owner == request.user:
            todo.delete()
            messages.add_message(request, messages.SUCCESS, "Todo deleted")
            return HttpResponseRedirect(reverse('todo:home'))
        return render(request, "todo/todo-delete.html", context)

    return render(request, "todo/todo-delete.html", context)


@login_required
def todo_edit(request, id):
    todo = get_object_or_404(Todo, pk=id)
    form = TodoForm(instance=todo)
    context = {
        'todo': todo,
        'form': form
    }

    if request.method == 'POST':
        title = request.POST.get('title')
        description = request.POST.get('description')
        is_completed = request.POST.get('is_completed', False)

        todo = Todo.objects.get(pk=id)
        todo.title = title
        todo.description = description
        todo.is_completed = True if is_completed == "on" else False

        if todo.owner == request.user:
            todo.save()

            messages.add_message(request, messages.SUCCESS, "Todo updated success")

            return HttpResponseRedirect(reverse('todo:todo-detail', kwargs={'id': todo.pk}))

    return render(request, "todo/todo-edit.html", context)

templates/todo/create-todo.html
{% extends '_partials/base.html' %}
{% block title %}
    Create todo
{% endblock %}
{% load static %}

{% block content %}
<h3>Create Todo</h3>
{% include '_partials/messages.html' %}
<form action="{% url 'todo:create-todo' %}" method="post" class="ui form">
    {% csrf_token %}
    {{form.as_p}}
    <input class="ui button primary" type="submit" value="Submit">
</form>

{% endblock %}

templates/todo/index.html
{% extends '../_partials/base.html' %}
{% block title %}
    Home
{% endblock %}
{% load static %}
{% block content %}
    <img src="{% static 'images/Logo.png' %}" alt="">
    <h1 class="ui header">My List of Todos</h1>
    {% include '_partials/messages.html' %}
    {% if todos %}
<table class="ui table">
    <thead>
    <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Complete</th>
        <th>Actions</th>
    </tr>
    </thead>
    <tbody>
        {% for todo in todos %}
        <tr>
            <td>{{todo.title}}</td>
            <td>{{todo.description}}</td>
            <td>
                {% if todo.is_completed %}
                YES <i class="check icon green"></i>
                {% else %}
                NO
                {% endif %}
            </td>
            <td>
                <a href="{% url 'todo:todo-detail' todo.pk %}" class="ui button">
                    <i class="eye icon"></i>
                </a>
                <a href="{% url 'todo:todo-edit' todo.pk %}" class="ui button">
                    <i class="pencil icon"></i>
                </a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
    <tfoot>
    <tr>
        <th>
            <a href="?filter=all">All {{all_count}}</a>
        </th>
        <th>
            <a href="?filter=incomplete">{{incomplete_count}} Remaining</a>
        </th>
        <th>
            <a href="?filter=complete">{{completed_count}} Completed</a>
        </th>
        <th></th>
    </tr>
    </tfoot>
</table>
    {% else %}
    <div class="ui message">
        <div class="header">
            No items yet
        </div>
        <p>You can create your first todo now <a href="{% url 'todo:create-todo' %}">Add new</a></p>
    </div>
    {% endif %}
{% endblock %}

templates/todo/todo-delete.html
{% extends '_partials/base.html' %}
{% block title %}
    Delete todo
{% endblock %}
{% load static %}

{% block content %}
<h1 class="ui header">Delete Todo?</h1>

<form action="{% url 'todo:todo-delete' todo.pk %}" class="ui form" method="post">
  {% csrf_token %}
  <p>Are you sure you want to delete this todo?</p>
  <input type="submit" value="YES" class="ui button negative">
  <a href="{% url 'todo:todo-detail' todo.pk %}">Cancel</a>
</form>
{% endblock %}

templates/todo/todo-detail.html
{% extends '_partials/base.html' %}

{% block title %}
    Todo: {{todo.title}}
{% endblock %}

{% block content %}
<h1 class="ui header">Todo Detail</h1>
    {% include '_partials/messages.html' %}
    <div class="ui card">
        <div class="content">
            <div class="header">{{todo.title}}</div>
            <div class="meta">{{todo.created_at}}</div>
            <div class="description">{{todo.description}}</div>
        </div>
        <div class="extra content">
            {% if todo.is_completed %}
                <p>
                <i class="check icon green">

            </i>
                Completed at {{todo.updated_at}}
            </p>
            {% else %}
                <p>Not yet completed</p>
            {% endif %}

            <a href="" class="ui button primary">Edit</a>
            <a href="{% url 'todo:todo-delete' todo.pk %}" class="ui button red">Delete this <todo></todo></a>
        </div>
    </div>
{% endblock %}

templates/todo/todo-edit.html
{% extends '_partials/base.html' %}
{% block title %}
    Todo: {{todo.title}}
{% endblock %}
{% load static %}

{% block content %}
<form action="{% url 'todo:todo-edit' todo.pk %}" method="post" class="ui form">
    {% csrf_token %}
    {{form.as_p}}
    <input class="ui button primary" type="submit" value="Save">
</form>

{% endblock %}