authentication/urls.py
from django.urls import path

from . import views


app_name = "authentication"

urlpatterns = [
    path('login/', views.login_user, name='login'),
    path('register/', views.register, name='register'),
    path('logout_user/', views.logout_user, name='logout_user'),
    path('activate-user/<uidb64>/<token>/', views.activate_user, name="activate"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todo.urls')),
    path('auth/', include('authentication.urls')),
]

handler404 = "helper.views.handle_not_found"
handler500 = "helper.views.handle_server_error"

authentication/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    is_email_verified = models.BooleanField(default=False)

    def __str__(self):
        return self.email

authentication/views.py
import threading

from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_text, force_bytes, force_str, DjangoUnicodeDecodeError
from django.core.mail import EmailMessage
from django.conf import settings

from validate_email import validate_email
import threading

from .models import User
from helper.decorators import auth_user_should_not_access
from .utils import generate_token                                                           


class EmailThread(threading.Thread):

    def __init__(self, email):
        self.email = email
        threading.Thread.__init__(self)

    def run(self) -> None:
        self.email.send()


def send_activation_email(request, user):
    current_site = get_current_site(request)
    email_subject = "Activate your account"
    email_body = render_to_string('authentication/activate.html', {
        'user': user,
        'domain': current_site,
        'uid': urlsafe_base64_encode(force_bytes(user.pk)),
        'token': generate_token.make_token(user)
    })

    email = EmailMessage(subject=email_subject, body=email_body
                 ,from_email=settings.EMAIL_FROM_USER
                 ,to=[user.email])

    if not settings.TESTING:
        EmailThread(email).start()


def register(request):
    if request.method == "POST":
        context = {
            'has_error': False,
            'data': request.POST
        }
        email = request.POST.get('email')
        username = request.POST.get('username')
        password = request.POST.get('password')
        password2 = request.POST.get('password2')

        if len(password) < 6:
            messages.add_message(request, messages.ERROR, 'Password should be at least 6 characters')
            context['has_error'] = True
        if password != password2:
            messages.add_message(request, messages.ERROR, 'Password mismatch')
            context['has_error'] = True
        if not validate_email(email):
            messages.add_message(request, messages.ERROR, 'Enter a valid email address')
            context['has_error'] = True
        if not username:
            messages.add_message(request, messages.ERROR, 'Username is required')
            context['has_error'] = True
        if User.objects.filter(username=username).exists():
            messages.add_message(request, messages.ERROR, 'Username is taken, choose another one')
            context['has_error'] = True
            return render(request, 'authentication/register.html', context, status=409)

        if User.objects.filter(email=email).exists():
            messages.add_message(request, messages.ERROR, 'Email is taken, choose another one')
            context['has_error'] = True
            return render(request, 'authentication/register.html', context, status=409)

        if context['has_error']:
            return render(request, 'authentication/register.html', context)

        user = User.objects.create_user(username=username,
                                        email=email)
        user.set_password(password)
        user.save()

        send_activation_email(request, user)

        messages.add_message(request, messages.SUCCESS, "We sent you an email to verify your account")
        return redirect('authentication:login')

    return render(request, 'authentication/register.html')


@auth_user_should_not_access
def login_user(request):
    context = {}
    if request.method == "POST":
        context.update({'data': request.POST})
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if not user.is_email_verified:
            messages.add_message(request, messages.ERROR, "Email is not verified, please check your email inbox")
            return render(request, 'authentication/login.html', context)

        if not user:
            messages.add_message(request, messages.ERROR, "invalid credentials")
            return render(request, 'authentication/login.html', context)

        login(request, user)
        messages.add_message(request, messages.SUCCESS, f"Welcome {user.username}")
        return redirect(reverse('todo:home'))
            

    return render(request, 'authentication/login.html')


def logout_user(request):

    logout(request)
    messages.add_message(request, messages.SUCCESS, "Successfully logged out")
    
    return redirect(reverse('authentication:login'))


def activate_user(request, uidb64, token):

    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(id=uid)

    except Exception as e:
        user = None

    if user and generate_token.check_token(user, token):
        user.is_email_verified = True
        user.save()

        messages.add_message(request, messages.SUCCESS, "Email verified, you can now login")
        
        return redirect(reverse('authentication:login'))

    return render(request, 'authentication/activate-failed.html', {"user": user})
        

templates/authentication/activate-failed.html
<p>Something went wrong with your link</p>

templates/authentication/activate.html
{% autoescape off %}


Hi {{user.username}}

Please use the link below to verify your account.

http://{{domain}}{% url 'authentication:activate' uidb64=uid token=token %}


{% endautoescape %}

templates/authentication/login.html
{% extends '_partials/base.html' %}

{% load static %}

{% block content %}
    <div class="ui grid">
        <div class="four wide column">

        </div>
        <div class="eight wide column">
            <div class="ui middle aligned center aligned grid">
                <div class="column mt-5">
                    <h2 class="ui teal image header">
                        <img src="{% static '' %}" alt="">
                        <div class="content">Log in</div>
                    </h2>

                    {% include '_partials/messages.html' %}

                    <form action="{% url 'authentication:login' %}" class="ui large form" method="post">
                        {% csrf_token %}
                        <div class="ui stacked segment">
                            <div class="field">
                                <div class="ui left icon input">
                                    <i class="user icon"></i>
                                    <input type="text" name="username" placeholder="Username" value="{{data.username}}">
                                </div>
                            </div>
                            <div class="field">
                                <div class="ui left icon input">
                                    <i class="user icon"></i>
                                    <input type="password" name="password" placeholder="Password" value="{{data.username}}">
                                </div>
                            </div>
                        </div>
                        <button class="ui fluid large teal submit button">Login</button>
                    </form>
                    <div class="ui message">
                        Dont have an account <a href="{% url 'authentication:register' %}">Sign up</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/authentication/register.html
{% extends "_partials/base.html" %}
{% block content %} {% load static %}

<div class="ui grid">
  <div class="four wide column"></div>
  <div class="eight wide column">
    <div class="ui middle aligned center aligned grid">
      <div class="column mt-5">
        <h2 class="ui teal image header">
          <img src={% static 'img/Logo.png' %} class="image" />
          <div class="content">Registration</div>
        </h2>

          {% include '_partials/messages.html'%}


        <form class="ui large form" method="post" action="{% url 'authentication:register' %}">
          {% csrf_token %}
          <div class="ui stacked segment">
            <div class="field">
              <div class="ui left icon input">
                <i class="user icon"></i>
                <input type="text" name="username" value="{{data.username}}"  placeholder="Username" />
              </div>
            </div>

            <div class="field">
              <div class="ui left icon input">
                <i class="user icon"></i>
                <input type="text" name="email" value="{{data.email}}" placeholder="E-mail address" />
              </div>
            </div>
            <div class="field">
              <div class="ui left icon input">
                <i class="lock icon"></i>
                <input type="password" name="password" placeholder="Password" />
              </div>
            </div>

            <div class="field">
              <div class="ui left icon input">
                <i class="lock icon"></i>
                <input
                  type="password"
                  name="password2"
                  placeholder="Repeat Password"
                />
              </div>
            </div>
            <button class="ui fluid large teal submit button">Submit</button>
          </div>

        </form>

        <div class="ui message">Have an account? <a href="">Login</a></div>
    <div class="four wide column"></div>
  </div>
</div>

{% endblock content %}